eureka:
  client:
    enabled: false
    service-url:
      defaultZone: "http://localhost:8761/eureka"

spring:
  application:
    name: "app-demo"
  config:
    import:
      - "optional:configserver:"
  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false
    config:
      enabled: true
      fail-fast: true
      discovery:
        enabled: true
        service-id: "config-server" 
