server:
  port: 8888

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: "http://localhost:8761/eureka"

spring:
  application:
    name: "config-server"
  profiles:
    active:
      - "native"
  cloud:
    consul:
      enabled: true
      host: "localhost"
      port: 8500
      discovery:
        enabled: true
    config:
      server:
        native:
          add-label-locations: false
          search-locations: "file:config/{application}"
